CREATE DATABASE RESTAURANT

USE RESTAURANT

CREATE TABLE MEALS
(
 ID INT PRIMARY KEY IDENTITY,
 NAME NVARCHAR(50) NOT NULL,
 PRICE MONEY 
)
CREATE TABLE CATEGORIES
(
    ID INT PRIMARY KEY IDENTITY,
    NAME NVARCHAR(50) NOT NULL
)
ALTER TABLE MEALS
ADD CATEGORIYID INT FOREIGN KEY REFERENCES CATEGORIES(ID)

ALTER TABLE MEALS
ADD CONSTRAINT CATEGORY_ID FOREIGN KEY (CATEGORIYID) REFERENCES MEALS(ID)

CREATE TABLE INGREDIENTS
(
    ID INT PRIMARY KEY IDENTITY,
    NAME NVARCHAR(50) NOT NULL
)

CREATE TABLE MEALINGREDIENTS
(
    MEALID INT FOREIGN KEY REFERENCES MEALS(ID),
    INGEDIENTID INT FOREIGN KEY REFERENCES INGREDIENTS(ID)

)
INSERT INTO CATEGORIES
VALUES
(N'SEHER YEMEYI'),
(N'GUNORTA YEMEYI'),
(N'AXSAM YEMEYI')

SELECT * FROM CATEGORIES

INSERT INTO MEALS(NAME,PRICE,CATEGORIYID)
VALUES
(N'POMIDOR YUMURTA',5,1),
(N'DUSBERE',7,2),
(N'XENGEL SETI',45,2),
(N'KABAB',23,2),
(N'SMETAN',3,1),
(N'KARTOF QIZARTMASI',4,2)

SELECT * FROM MEALS

INSERT INTO INGREDIENTS
VALUES
(N'POMIDOR'),
(N'XEMIR'),
(N'ET'),
(N'QATIQ'),
(N'KARTOF'),
(N'YUMURTA')

INSERT INTO MEALINGREDIENTS
VALUES
(1,1),
(1,6),
(2,2),
(3,2),
(4,3),
(5,4),
(6,5)

SELECT * FROM MEALINGREDIENTS


-- Bütün yeməkləri yanında ingredient sayı ilə birlikdə select edən query
SELECT * , (SELECT COUNT(*) FROM MEALINGREDIENTS AS MI WHERE MI.MEALID=M.ID ) AS INGREDIENTSCOUNT FROM MEALS AS M

-- Bütün category-ləri yanında o kateqoriyadaki ən bahalı və ən ucuz yemək qiyməti ilə select edən query

SELECT 
    ID ,
    NAME ,
    (SELECT MIN(PRICE) FROM MEALS AS M WHERE M.CATEGORIYID = C.ID) AS ENUCUZ,
    (SELECT MAX(PRICE) FROM MEALS AS M WHERE M.CATEGORIYID = C.ID) AS ENBAHA
FROM 
    CATEGORIES AS C;

-- Bütün yemekləri select edib yanında category adını da göstərən query

SELECT * ,
(SELECT C.NAME FROM CATEGORIES AS C WHERE C.ID=M.CATEGORIYID) AS CATEGORYNAME
FROM MEALS AS M

-- Hec bir yeməyi olmayan katqoriyaları select edən query

SELECT * FROM CATEGORIES AS C WHERE NOT EXISTS(SELECT * FROM MEALS AS M WHERE C.ID=M.CATEGORIYID)

